### ISSUE TITLE
Suggestion: Rename tables to queries or jobs

### ISSUE THREAD

**Issue by svki0001** [karolisdailidonis/DORM#6]
The property name `tables` might be confusing, if all they contain are sql queries. 

I suggest renaming the property `tables` to `queries`,  `jobs`, `requests` or `requestJobs`.

When changing the property name, backwards compatibility or responding a version error would be nice.

**Comment by karolisdailidonis** [comment]
wording update [0bea9a0](https://github.com/karolisdailidonis/DORM/commit/0bea9a0cf89f212868813eb0d826585deaaec11d):

"tables" => "jobs"
"requestJob" => "job"
